name: Open Google

on:
  push:
    branches: [ main ]

jobs:
  open-url:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: openai/action-open-url@v1
      with:
        url: 'https://www.google.com'
